### PR TITLE
Button: Add ability to add data attributes to DOM

### PR DESCRIPTION
**Pull request by ButuzGOL**
### Additional description

Add Button data attrs

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [x] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [x] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [x] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [x] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [x] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [x] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by interactivellama** [comment]
@ButuzGOL Please provide the reason for usage of data attributes. Is this for compatibility with another library? This is the first time this has been requested in this library that has existed for 2+ years.

https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html#should-i-keep-data-in-custom-attributes

**Comment by ButuzGOL** [comment]
For automation we are using data-id attr 
we won't use "id" prop as our wrapper component which has button component can be multiple on same page

**Comment by interactivellama** [comment]
I understand. This looks like a very specific use case. Let me think about this. I would prefer something more generic. Like [this pull request](https://github.com/ant-design/ant-design/pull/10922/files), but let me get back to you on it.

**Comment by ButuzGOL** [comment]
If ok to have data-attrs i can rebuild this pull as in [this pull request](https://github.com/ant-design/ant-design/pull/10922/files)

**Comment by interactivellama** [comment]
You are welcome to go ahead and work on that type of utility, but I would like at least a day to decide on the architecture of this and make sure it's the best route to go. So far I've only spent around 15 min thinking about. By adding this to `Button`, we are opening the addition of it to all components, etc. I don't want to have break stuff in the future.

**Comment by interactivellama** [comment]
@ButuzGOL Let's proceed with a similar reduce function and DOM element spread as Ant Design.

We will want to add something to the component description [here](https://github.com/salesforce/design-system-react/blob/master/components/button/index.jsx#L30). Something like 

> Any text passed into `data-*`, `aria-`` or `role` props will be added to the element with `.slds-button`.

Please add similar tests in Mocha. Looking forward to seeing your work! I'm sure you aren't the only one wanting to do this.

**Comment by interactivellama** [comment]
Moving to issue #1544

**Pull request closed without merging**
