### PR TITLE
Icon Button: Adds background

### LINKED ISSUE #2027: Icon Button: Missing background color
Some of the icon buttons have transparent backgrounds. I noticed this in page header the other day, but it looks like Button stateful has it, too.

Screen Shot 2019-06-10 at 10 45 46 AM

Anyone is free to pick this up.

http://design-system-react-components.herokuapp.com/?selectedKind=SLDSButtonStateful&selectedStory=Icon&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

### PR DESCRIPTION
**Pull request by pulkonet**
Fixes #2027 

### Additional description

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [ ] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [ ] `npm run lint:fix` has been run and linting passes.
* [ ] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by interactivellama** [comment]
It looks like snapshots need to be updated.

@kevinparkerson This looks like the bug in PageHeader that we saw.

**Comment by pulkonet** [comment]
@interactivellama Yes, the snapshots need to be updated, I will update them once you confirm this is the correct way forward.

**Comment by interactivellama** [comment]
Yes, this is correct based on https://lightningdesignsystem.com/components/button-icons/#Icon-Containers

**Comment by interactivellama** [comment]
Please update from master branch to fix DeepScan analysis.

**Comment by kevinparkerson** [comment]
> @kevinparkerson This looks like the bug in PageHeader that we saw.

@interactivellama Yup, it is. As @pulkonet said, `icon-fixx`slds-button_icon-border-filled` is the solution, though I would like to point out that button has both "border" and "border-filled" variants:

```
/**
 * For icon variants, please reference <a href="http://www.lightningdesignsystem.com/components/buttons/#icon">Lightning Design System Icons</a>.
 */
iconVariant: PropTypes.oneOf([
	'bare',
	'container',
	'border',
	'border-filled',
	'brand',
	'more',
	'global-header',
]),
```

Perhaps we should follow suit here, keeping the original class for border, and adding an additional "border-filled" variant with the other class?

**Comment by interactivellama** [comment]
@kevinparkerson I'm not understanding. 

`border-filled` doesn't look like a recent addition from https://lightningdesignsystem.com/release-notes/ .

The Button icon component is required to have slds-button—icon applied to the <button /> element. Before, slds-button—icon-inverse, slds-button—icon-container, slds-button—icon-border, slds-button—icon-border-filled, slds-button—icon-border-inverse, slds-button—icon-more, and slds-button—icon-error were used in conjunction with the slds-button classname but we now require slds-button—icon to be a part of this grouping of classnames

**Comment by kevinparkerson** [comment]
@interactivellama basically all I'm saying is we might need some way to have both filled and transparent button icons. @pulkonet's code is currently using filled if the button is of variant `icon`, but SLDS shows both filled and unfilled icon buttons here:

https://lightningdesignsystem.com/components/button-icons/#Disabled-2

Screen Shot 2019-06-26 at 9 08 52 PM

**Comment by interactivellama** [comment]
I understand. I guess the fact that it’s an icon should control the fill. Maybe the buttons were transparent before and I just couldn't tell because the background color was white previously.

Can someone propose a solution?

**Comment by kevinparkerson** [comment]
@interactivellama perhaps we have an `icon-filled` variant that uses the filled style?

**Comment by interactivellama** [comment]
@kevinparkerson Yes, that sounds good. @pulkonet  Please add `icon-filled` variant to `ButtonStateful` and update the story to use that variant.

**Comment by interactivellama** [comment]
Thank you @pulkonet for stepping in, diagnosing the bug and adding this feature.

**Pull request merged**
