### PR TITLE
Update react-modal from 3.13.1 to 3.14.2 to add bugfix-PR 7e732d7 Wrapping getComputedStyle i…

### PR DESCRIPTION
**Pull request by beekermememe**
This request is to update the react-modal package to 3.14.2 - the fix this targets is - https://github.com/reactjs/react-modal/pull/864
Fixes #
This fixes an issue where using the slds-modal, and the modal contains an iframe which in turn contains webcomponents, the modal does not lock focus to the modal

### Additional description

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [ done] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [done ] `npm run lint:fix` has been run and linting passes.
* [ done] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [NA ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [done ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ done] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [done ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by beekermememe** [comment]
Signed the CLA

**Comment by beekermememe** [comment]
not sure what is going on here, running the test:unit locally passes

**Comment by interactivellama** [comment]
First, thank you for the package update. The Mocha-based browser appear to be failing in the CI https://github.com/salesforce/design-system-react/issues/2753 

I did a check on `npm start` -> `http://localhost:8001/` and modal tests passed before the update and failed afterward.
Screen Shot 2021-06-10 at 5 13 13 PM

**Comment by interactivellama** [comment]
And before the package update

Screen Shot 2021-06-10 at 5 16 33 PM

Different tests fail when run, so this looks like a race condition on whether the modal is mounted or not.

**Comment by interactivellama** [comment]
Thanks for the test update. Will review.

**Review by interactivellama — APPROVED** [review]

**Pull request merged**
