### PR TITLE
[Work in progress - do not review] Add disabled key to options menu items in Combobox component

### LINKED ISSUE #1635: Allow accessible, disabled menu items in combobox
Accessibility team and lightning dashboard are requesting this. I'm willing to work on it. 

They currently use the lookup component. Should we create a PR to fix it on the deprecated component so they can be unblocked?

I told them that they should probably upgrade to use the combobox but they might not have time before feature freeze.

@interactivellama What do you think? I can create a PR to have both attributes on both components.

### PR DESCRIPTION
**Pull request by davidlygagnon**
Fixes #1635

### Additional description

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [ ] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [ ] `npm run lint:fix` has been run and linting passes.
* [ ] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by davidlygagnon** [comment]
Todo: `aria-describedby` and `tooltip`.

**Comment by davidlygagnon** [comment]
I'm working on adding a tooltip for disabled items and I'm debating between the following:

screen shot 2018-11-06 at 11 34 17 pm

screen shot 2018-11-06 at 11 44 02 pm

In the first case,  we would let the consumer pass in`option.tooltip` which is a tooltip component that can have children or not. It would be fixed in place in front of the menu item `span` tree.

In the second case, we don't have the option for `option.tooltip` and we only wrap the menu item with a tooltip where they can set the content label.

@interactivellama What do you think would be the best approach?

Also another question is about SLDS classes: 

It seems there's a gap in supporting disabling menu items in the CSS. I couldn't find a rule to disabling hovering of disabled items and setting back the cursor to default. Should I make a PR in SLDS repo?

```
.slds-listbox__item > span[aria-disabled=“true”]:hover {
    background-color: transparent; 
    cursor: default;
}
```

**Comment by interactivellama** [comment]
@davidlygagnon We need to add the disabled items back into the option index, so they can be read by arrow key down through by a screen reader for example.

**Comment by davidlygagnon** [comment]
A few notes about recommendations from SLDS:

1. There shouldn't be a new icon for disabled items.
2. A tooltip should be present on the menu item (since there's no disable icon).
3. In the case that there is already a custom icon on the menu item, possibly allow a different style for that icon to represent a disabled state.
4. SLDS will create a work item to add tokens/styles for disable menu items that we should consume in DSR.
5. Cursor should be set to default.
6. Tooltip should show up as soon as we hover on menu item. Tooltip content should be readable by screen-readers.

**Comment by interactivellama** [comment]
@davidlygagnon Sounds good to me.

In response, I'd recommend adding a `options.tooltip: <Tooltip />` and a `disabled` key that will have it's `children` overwritten by default with the "menu item".

```
option.disabled: true
options.tooltip: <Tooltip />
```

**Comment by kwilloughby-sf** [comment]
The SLDS work item has been created.

https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000065CXlIAM/view

**Comment by davidlygagnon** [comment]
Yup - that's fine, thanks. I'll wait till mid Jan to resume this.

**Pull request closed without merging**
