### PR TITLE
Updated SLDS to 2.8.3 in DSR

### LINKED ISSUE #1743: Update SLDS to 2.8.3

### PR DESCRIPTION
**Pull request by kevinparkerson**
Fixes #1743

Tests pass and based on a manual scan of the components everything appears to be in order.

NOTE: I was having a ton of trouble getting tests to pass locally in the terminal. Part of the solution seemed to be running the following:
`node --max_old_space_size=4096`
I'm unsure if this was my machine's own unique issue or if it will happen to others running DSR locally. That command may need to be added to the test script for Travis CI. If we find it to be a problem I can do just that!

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [x] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [x] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [x] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [x] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [x] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [x] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by kevinparkerson** [comment]
@interactivellama question: does the `peerDependencies` listing for SLDS need to be updated as well? It was already ahead of the actual version of SLDS listed in DSR's `devDependencies` section:
```
"peerDependencies": {
		"@salesforce-ux/design-system": "^2.7.4",
		"react": ">=15.4.1 <17",
		"react-dom": ">=15.4.1 <17"
	},
```

**Comment by interactivellama** [comment]
The dev section is for our dev work, tests, etc. The peer dependencies are for our consumers, so they will get an npm warning as what the project has been tested with.

It's looks like you found a bug, they should match.

**Comment by futuremint** [comment]
The "Image Snapshots › Image storyshots › SLDSDataTable › Basic (Fluid Layout)" snapshot is failing.

**Comment by kevinparkerson** [comment]
@futuremint does that happen locally for you? Locally everything passes for me, but Travis is having issues

**Pull request closed without merging**
