### PR TITLE
Include all snapshot tests

### LINKED ISSUE #2067: Snapshot tests do not include the test files under components
When using `npm run test:snapshot`, or `npm run test`, snapshot tests under `/components` are not included in the test. This can be verified by adding the `--listTests` to the JEST command:

```
$ npx jest --config=tests/snapshots-config.json --listTests
.../design-system-react/tests/story-based-tests.snapshot-test.js
```

This happens because JEST uses the location of the config file (i.e. `/tests/`) as the root directory.

I would like to work on this issue myself. Please feel free to assign it to me and I am going to upload a PR soon.

### PR DESCRIPTION
**Pull request by hajiz**
Fixes #2067

### Additional description

Updated the config file, so that it uses the project root as the root folder. This was the regex for test files will match all the snapshot tests, and not just the ones under tests folder.

Here's the result of test list before and then after the fix:

Before:
```
$ npx jest --config=tests/snapshots-config.json --listTests
.../design-system-react/tests/story-based-tests.snapshot-test.js
```
After:
```
$ npx jest --config=tests/snapshots-config.json --listTests
.../design-system-react/tests/story-based-tests.snapshot-test.js
.../design-system-react/components/date-picker/__tests__/datepicker.snapshot-test.jsx
.../design-system-react/components/icon/__tests__/icon.snapshot-test.jsx
.../design-system-react/components/radio-button-group/__tests__/radio-button-group.snapshot-test.jsx
.../design-system-react/components/radio-group/__tests__/radio-group.snapshot-test.jsx
.../design-system-react/components/toast/__tests__/toast.snapshot-test.jsx
.../design-system-react/components/vertical-navigation/__tests__/navigation.snapshot-test.jsx
.../design-system-react/components/slider/__tests__/slider.snapshot-test.jsx
.../design-system-react/components/split-view/__tests__/split-view.snapshot-test.jsx
.../design-system-react/components/progress-ring/__tests__/progress-ring.snapshot-test.jsx
.../design-system-react/components/pill/__tests__/pill.snapshot-test.jsx
.../design-system-react/components/breadcrumb/__tests__/bread-crumb.snapshot-test.jsx
.../design-system-react/components/panel/__tests__/filtering.snapshot-test.jsx
```

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [X] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [X] `npm run lint:fix` has been run and linting passes.
* [X] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [X] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by hajiz** [comment]
Some of the items, like test for new props, etc, are not applicable to this PR. Should I just check them off? Thanks

**Comment by hajiz** [comment]
@minevskiy @interactivellama please take a look. I will resolve the merge conflict shortly

**Comment by interactivellama** [comment]
Thank you for finding this bug! Contributors have been slowly adding snapshots via StoryShots Storybook add-on over the past year. This removes the need for most of the one off tests you have re-added to the test suite.

Please delete the test files for the following components and squash commits (so that the extra PNGs aren't in git history), since these are now in Storybook-based DOM snapshots or in the open PR https://github.com/salesforce/design-system-react/pull/1987

* Icon
* breadcrumb
* Dropdown
* Pill
* ProgressRing
* Search
* Slider
* SplitView

That leaves the following in this pull requests.

`.../design-system-react/components/date-picker/__tests__/datepicker.snapshot-test.jsx`
`.../design-system-react/components/panel/__tests__/filtering.snapshot-test.jsx`

**Comment by interactivellama** [comment]
@hajiz Unless you've already started working on modifying this branch as mentioned above. I'm going to make this a part of #2096.

**Comment by interactivellama** [comment]
Closing in favor of #2097

**Comment by interactivellama** [comment]
@hajiz 

> Some of the items, like test for new props, etc, are not applicable to this PR. Should I just check them off? Thanks

No, it's primarily a checklist so new contributors don't miss checking things or have to look through the CI tests.

**Comment by hajiz** [comment]
Thanks Stephan for taking care of this, and sorry for my late responds. I'm glad you took over because I didn't have the knowledge to do exactly as you mentioned. I'm still learning...

**Pull request closed without merging**
