### PR TITLE
add success color variant to icon component

### PR DESCRIPTION
**Pull request by no-stack-dub-sack**
The current icon component is missing the success color variant. This PR adds it.

### Additional description

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [x] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [x] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [x] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] CircleCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by no-stack-dub-sack** [comment]
I think there's some work that would need to be done here in terms of testing but wanted to get the conversation going before tackling all of that. Thanks.

**Comment by interactivellama** [comment]
Yes, this is great add! 

Yes, an example added to Jest DOM snapshots via a storybook story would be sufficient as a test.

**Comment by no-stack-dub-sack** [comment]
@interactivellama great. I'll take a look this week and get the tests added. Thanks!

**Comment by no-stack-dub-sack** [comment]
@interactivellama can you give the latest commits a review and let me know if this covers it? after running `npm test` from what I can tell everything passed and I can see the snapshot was created based on the example I added. 

That said I didn't see a corresponding PNG get generated so not quite sure how that works / if I'm missing something there.

Also, didn't want to change anything fundamental here, but I was unable to run `npm test` locally without modifying [the script](https://github.com/salesforce/design-system-react/blob/c049ca107a0ff6cdba1375ebd1a09546f941480f/package.json#L33):

```diff
+ "test": "npm run prepare-components && npm run test:banner && npx concurrently..."
- "test": "npm run prepare-components; npm run test:banner && npx concurrently..."
```

Thanks, and happy holidays!

**Comment by interactivellama** [comment]
Thanks for the follow-up. There's no PNG, we do not do VRT testing any more. At first glance, this looks great. I'll try to look at in the next week. Might me a little tricky with the holidays/Christmas.

**Comment by no-stack-dub-sack** [comment]
Yup, no rush at all. Just had the time as things were winding down at work for the holidays.

Thanks!

**Comment by no-stack-dub-sack** [comment]
@interactivellama Happy new year! Just checking in on this. Thanks!

**Review by interactivellama — DISMISSED** [review]

**Comment by interactivellama** [comment]
Thanks for the contribution. 0.10.43 is out!

**Comment by no-stack-dub-sack** [comment]
@interactivellama awesome, thanks!

**Pull request merged**
