### PR TITLE
Add Activity Timeline Component

### LINKED ISSUE #1857: Add Activity Timeline Component
Implement the Activity Timeline component according to spec: https://www.lightningdesignsystem.com/components/activity-timeline/

### PR DESCRIPTION
**Pull request by aswinshenoy**
Fixes #1857 

### Additional description
Initial Proposal for the Activity Timeline Component

**Screenshot**
screenshot

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [ ] `npm run lint:fix` has been run and linting passes.
* [ ] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by aswinshenoy** [comment]
According to my first proposal, a typical example would look somewhat like this -
```jsx
<ActivityTimeline>
	<Activity  
		  type="task"
		  title={...}
		  action={...}
		  time={...}
		  description="..."
		  name={...}
		  related={...}
		  isRecurring
	/>
	<Activity  
		  type="call"
		  title={...}
		  action={...}
		  time={...}
		  description="..."
		  name={...}
		  related={...}
	/>
	<Activity  
		  type="email"
		  title={...}
		  action={...}
		  time={...}
		  description="..."
		  sender={...}
		  recipient={...}
		  hasAttachment
		  groupEmail
	/>
	<Activity  
		  type="event"
		  title={...}
		  action={...}
		  time={...}
		  description="..."
		  location={...}
		  attendees={...}
  		  when={...}
	/>
</ActivityTimeline>
```
As one can see, there are so many `object` type props specific for each type of event. I was thinking whether we should have a more flexible and customizable detail set - something like
```json
		  [
			 {
				 "title" : "Name"
				 "detail":  {...}
			 },
			 {
				 "title" : "Related To"
				 "detail":  {...}
			 },
			 {
				 "title" : "Location"
				 "detail":  {...}
			 },
		  ]
```

**Comment by kevinparkerson** [comment]
@aswinshenoy currently failing Travis tests, apparently due to lint issues. Please run `npm run lint:fix`, commit, and push when you get a chance

**Comment by kevinparkerson** [comment]
@aswinshenoy I agree, an array for the sub-items would be simpler and easier to use for the developer, similar to the `options` seen here: https://react.lightningdesignsystem.com/components/menu-dropdowns/

**Comment by interactivellama** [comment]
First, there are many different object shapes going on here and mapping the data to the UI is a difficult task and the SLDS website doesn't show the full options unfortunately.

That tipping point for components vs data collections is typically based on:
* How much custom markup is going to be used. Items in a menu list are typically similar for instance. The different types of activities have different shapes, so this will be difficult to validate.
* Length of data, consider data table row lengths and tree nested objects. Activity Timelines often have 10+ items.

The markup looks very consistent per type, so that makes an `options` OK. All the links are going to need `onClick` events though.

"You created an event with Aida Lee and 5 others" needs to be able to be internationalized, and the you have an `onClick` and Aida Lee and we will need to get to the number 5 somehow.

If we go with an `options` array, we will want to be able to test the shape of the object with propTypes. The easiest way to make sure the shape is correct would probably be passing the details into an sub components such as `ActivityTimelineEmail` and `ActivityTimelineTask`.

This would also allow custom activities that we don't know about in the future. I know for certain that there are more activities than those that are on the SLDS website.

I'd probably do something like this:
```
const options = [
    {
        id: '1',
        type: 'task',
        details: {
            title: 'Review proposals for EBC deck with larger team and have marketing review this'
            
        }
    }
]

const onClickTitle = (event, { id }) => {console.log(`item ${id} clicked.`)};

const activityTimeLineSubComponents = {
    task: (detailsObject) => (<ActivityTimelineTask details={detailsObject}
        actionDropdown={<Dropdown />}
        checkbox={<Checkbox checked={detailsObject.checked}/>}
        events={{
            onClickTitle={onClickTitle}
        }}
        expanded
        // These subheading are so complicated, I don't want want to get into how to map the object shape into the UI.
        onRenderSubHeading={(detailsObject) => (<a href="javascript:void(0);">You</a> created a task with <a href="javascript:void(0);">Charlie Gomez</a>}} 
    />)
}

<ActivityTimeline>
    {options.map((item) => activityTimeLineSubComponents[item.type]))}
</ActivityTimeline>
```

There are many, many ways that the subheading can be done. I'm not quite sure how to internationalize it either.

Screen Shot 2019-03-22 at 6 12 37 PM

@kevinparkerson @aswinshenoy What do you all think? There are still `assistiveText` and `labels:` objects to propose, since all text needs to be able to be internationalized. This is going to be a large props spec.

**Comment by interactivellama** [comment]
Removing from Google Summer of Code 2019 proposal timeline. Will follow up with additional time after Expression and Tree Grid.

@aswinshenoy  Please re-open if work begins again.

**Pull request closed without merging**
