### PR TITLE
App Launcher Refactor and Add Expandable Section component

### LINKED ISSUE #1648: App Launcher: Align markup and UX pattern to SLDS
App Launcher has not been updated in two years. It should be updated to current SLDS UX patterns and flexibly meet the needs of any product planning to use it.

https://www.lightningdesignsystem.com/components/app-launcher/
* Align to current SLDS markup and design
* Align to current SLDS UX patterns
* Review Salesforce platform navigation use to be aware of common UX patterns.
* Fix all accessibility issues and move to production component

## Errata
* Ramp up, no tests, get UX patterns correct for Demo work
* Expand arrow is broken, also it should fill entire width
* Add items list (new API)
* Don't need drag and drop (for now)
* Implement Expandable Section as private sub component https://www.lightningdesignsystem.com/components/expandable-section/

### PR DESCRIPTION
**Pull request by kevinparkerson**
Fixes #1648 & #1361

NOTES:
- changed Modal getModal wrapper to section tag from div tag
- added className prop to be able to pass custom modal styles to the getModal wrapper element
- switched where app launcher's "modalClassName" prop applies classes (it was passing it to containerClassName for the modal, now it passes to className)
- Added role="button" & tabindex="0" to the tile div tag because it was yelling about accessibility

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [x] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [x] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [x] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [x] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [x] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [x] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by kevinparkerson** [comment]
Let me know if there's anything I missed in regards to setting up the new component (expandable-section) and switching app-launcher to prod status

**Comment by tanhengyeow** [comment]
Hi @kevinparkerson 

Nice to meet you :) I was thinking if you would like help to refactor the `Expandable Section` component on its own in a separate PR.

I believe it is a common component that can be consumed by other components too other than the `App Launcher`. It also helps to improve the separation of concerns for this PR. Let me know if that is a good idea, thanks 😄

**Comment by kevinparkerson** [comment]
Hi @tanhengyeow!

Nice to meet you as well. This PR creates ExpandableSection as a root-level component, with AppLauncherExpandableSection being a wrapper around that component with special formatting for children. Since AppLauncherExpandableSection has limited code itself and depends on ExpandableSection @interactivellama and I decided that ExpandableSection would just be a part of this PR for simplicity. I didn't realize ExpandableSection had an issue though, so thank you for pointing it out! I'll reference it with this PR.

**Comment by interactivellama** [comment]
#1821 Needs to go in before this.

**Pull request merged**
