### PR TITLE
Modal: fix error with dismissModalOnClickOutside

### LINKED ISSUE #1954: Modal: dismissOnClickOutside cannot be set to false to override disableClose
The Modal component determines if it should dismiss itself on outside clicks via this ternary expression:
 
``` javascript
		const dismissOnClickOutside = this.props.dismissOnClickOutside
			? this.props.dismissOnClickOutside
			: !this.props.disableClose;
```

When setting `dismissOnClickOutside` to false, it is equivalent to `false ? false : true` and will not evaluate to the value of `this.props.dismissOnClickOutside`. 

I'll send a PR over on Monday.

### PR DESCRIPTION
**Pull request by mattlysf**
Fixes #1954
---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [x] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [x] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [x] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [x] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [x] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [x] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by mattlysf** [comment]
so for whatever reason, your bot tagged my personal github account for the CLA, not this one I use for work and will be contributing under.

**Comment by interactivellama** [comment]
@mattly It probably has to do with the commit email and what emails you have listed in your github account.

**Comment by interactivellama** [comment]
@mattly Thank you for catching this bug. At this point, I plan to release a patch release next week.

**Comment by mattlysf** [comment]
> @mattly It probably has to do with the commit email and what emails you have listed in your github account.

Ah yeah that would have done it. I need to figure out how to modify my .gitconfig by hostname and still sync it between computers.

**Pull request merged**
