### PR TITLE
Fix bug with sortable causing focusable attribute to throw an error

### LINKED ISSUE #1328: Received `true` for a non-boolean attribute `focusable`
Setting `sortable` to `{true}` on a `DataTableColumn`
causes the following error
```
index.js:2178 Warning: Received `true` for a non-boolean attribute `focusable`.

If you want to write it to the DOM, pass a string instead: focusable="true" or focusable={value.toString()}.
    in th (created by SLDSDataTableHeaderCell)
    in SLDSDataTableHeaderCell (created by SLDSDataTableHead)
    in tr (created by SLDSDataTableHead)
    in thead (created by SLDSDataTableHead)
    in SLDSDataTableHead (created by SLDSDataTable)
    in table (created by SLDSDataTable)
    in SLDSDataTable (at WhitelistedTargetObjects.js:71)
    in div (created by SLDSCardBody)
    in SLDSCardBody (created by SLDSCard)
    in article (created by SLDSCard)
    in SLDSCard (at WhitelistedTargetObjects.js:57)
    in div (at WhitelistedTargetObjects.js:56)
    in CardExample (at App.js:31)
    in div (at App.js:27)
    in div (at App.js:22)
    in SLDSIconSettings (at App.js:21)
    in App (at index.js:8)
```
which is caused by `focusable={sortable ? true : null}` in `header-cell.jsx`

### PR DESCRIPTION
**Pull request by celador**
Fixes #1328
focusable attribute on the `th` of `header-cell.js` must be a boolean, cannot be null

### Additional description

---

### Pull Request Review checklist (do not remove)

* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at snapshot strings.
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by interactivellama** [comment]
Great find. I can merge if CI passes. Please run `npm run lint:fix` and sign the CLA.

**Comment by celador** [comment]
All checks have passed

**Comment by interactivellama** [comment]
Thanks. Please remove unrelated storyshot change that was committed.

https://github.com/celador/design-system-react/blob/2e4b41e6073649339529c8c824d57dce47014b1c/tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-inital-blank-story-placeholder-1-snap.png

**Comment by interactivellama** [comment]
Thanks!

**Pull request merged**
