### PR TITLE
Prevent onSelect callback when menu-list ListItem has property 'disab…

### LINKED ISSUE #2987: Disabled option of the Dropdown component triggers the onSelect event
Steps to repro the problem:
1. Follow https://github.com/salesforce/design-system-react/blob/master/docs/create-react-app.md to create a test app
2. Copy the very first example in https://react.lightningdesignsystem.com/components/menu-dropdowns/ into the App.js as follows:
```
import './App.css';

import { Dropdown, IconSettings } from "@salesforce/design-system-react";

function App() {
  return (
    <div className="App">
      <IconSettings iconPath="/icons">
        <Dropdown
          assistiveText={{ icon: "More Options" }}
          iconCategory="utility"
          iconName="down"
          iconVariant="border-filled"
          onSelect={(value) => {
            console.log("selected: ", value);
          }}
          options={[
            { label: "Menu Item One", value: "A0" },
            { label: "Menu Item Two", value: "B0", disabled: true },
            { label: "Menu Item Three", value: "C0" },
            { type: "divider" },
            { label: "Menu Item Four", value: "D0" },
            { label: "Menu Item Five", value: "E0" },
            { label: "Menu Item Six", value: "F0" },
            { type: "divider" },
            { label: "Menu Item Seven", value: "G0" },
          ]}
        />
      </IconSettings>
    </div>
  );
}

export default App;
```
3. Now the app should render a dropdown with some options. Open the developer console and click each option and notice it logs the clicked option to console.
4. Notice the second option in the dropdown is a disabled option, but clicking on this also logs to the console, meaning a disabled item is triggering the click events which is not expected.

### PR DESCRIPTION
**Pull request by rinkstiekema**
Fixes #2987

### Additional description
Introduced the `disabled` property in `item.d.ts` on the Props. It was already used in the menu-list but was missing from the typescript declaration. 

Changes affect the `handleClick` function.
```
	handleClick = (event) => {
		if (
			this.props.type !== 'link' ||
			this.props.href === 'javascript:void(0);' || // eslint-disable-line no-script-url
			this.props.href === '#'
		) {
			EventUtil.trapImmediate(event);
		}

		if (this.props.onSelect && !this.props.disabled) {
			this.props.onSelect(this.props.index);
		}
	};
```

The `disabled` property is used to prevent calling `onSelect`. I was unsure if it also should call `EventUtil.trapImmediate(event)` if the item is disabled. This could be added in the if statement if necessary.

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [x] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [x] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [x] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [x] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [x] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [x] CircleCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [x] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [x] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [x] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [x] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by rinkstiekema** [comment]
I have signed the CLA but the process failed somewhere along the way - the check is not being updated now. When I try the process again, it says I already signed the CLA.

**Comment by rinkstiekema** [comment]
Bump

**Comment by rinkstiekema** [comment]
Bump

**Review by lyy011lyy — APPROVED** [review]
Thanks for fixing this !
I don't think I have the access to approve.. but still try it as this fix is important to our project.

**Review by interactivellama — APPROVED** [review]

**Comment by interactivellama** [comment]
Looks good. Yes, this appears to be an oversight, since the keyboard does not select and `disabled` is supported at an item level

**Pull request merged**
