### PR TITLE
Modify Readme

### PR DESCRIPTION
**Pull request by iamnickvolpe**
Small change to documentation. When trying to pull this into "Create React App," it wasn't possible to import individual .JSX files. Also, it wasn't clear that SLDS needed to be imported as well.

---

### Pull Request Review checklist (do not remove)

* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at snapshot strings.
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by iamnickvolpe** [comment]
I just signed the CLA. Does someone need to kick off a retest?

**Comment by interactivellama** [comment]
I'd prefer folks not use the `design-system-react.js` bundled file in anything but a throw away prototype. Is that the only one that you were able to get working?

**Comment by iamnickvolpe** [comment]
@interactivellama I thought the same thing, but yeah, at least with create-react-app, it's the only thing that seemed to work for me. @amyleesalesforce tried a few things, too and I think she came up with the same thing.

**Comment by interactivellama** [comment]
Closing feel free to re-open with "Usage with Create React App" doc at `docs/create-react-app.md`.

**Pull request closed without merging**
