### PR TITLE
Add PortalSettings Component to allow custom portal DOM placement

### LINKED ISSUE #2866: Portal "Settings"/Destination Context for overflowBoundaryElement
I have a need to portal all menus/dialogs to a specific destination rather than the current default of `body`. 

This is because we are using design-system-react + slds in a visualforce page that supports both Salesforce classic and lightning. In order to do this we must use the slds with a custom scope, generated here: https://tools.lightningdesignsystem.com/css-customizer . With the custom scoped css, appending slds items to `body`, like the current portal implementation, results in slds css not applying them.

The proposed solution would be a new component that is modeled after the icon-settings component. 

```
PortalSettings.propTypes = {
	/**
	 * Selector for the destination container for portal elements
	 * example: `#portal-destination`
	 */
	renderTo: PropTypes.string,
};
```

This would then use a new React Context provider to send the destination to the existing `portal.jsx` component and if set, use that destination for the portal parent node.

The goal of this would be to have the usage of the optional component look like:
```
<IconSettings iconPath="/assets/icons">
	<PortalSettings renderTo="#portal-destination">
```

then all components that use `menuPosition="overflowBoundaryElement"`, will be portal'ed to a element within the scoped css.

### PR DESCRIPTION
**Pull request by mtetlow**
Implementing portal settings component to provide app wide context for the portal parent node

This is modeled on the existing icon settings component.

Fixes #2866

### Additional description

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [x] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [x] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [x] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [x] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [x] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by mtetlow** [comment]
@interactivellama it looks like the checks have passed so I am mentioning you per the "adding a new component" section of the contributing guidelines.

Looking forward to a review on this! It will help my team out a lot.

**Comment by interactivellama** [comment]
@mtetlow Looks good! Nice way to problem solve.

**Comment by interactivellama** [comment]
Please update the branch and I will merge.

**Comment by mtetlow** [comment]
Updated and ready to merge. Thanks @interactivellama !

**Review by interactivellama — APPROVED** [review]

**Pull request merged**
