### PR TITLE
Upgrade library to SLDS 2.9.x

### LINKED ISSUE #2080: Upgrade library to SLDS 2.9.x
Peer and dev dependency is out of date. The latest 2.x version of SLDS is 2.9.3

### PR DESCRIPTION
**Pull request by interactivellama**
Fixes #2080

### Additional description

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [ ] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [ ] `npm run lint:fix` has been run and linting passes.
* [ ] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by interactivellama** [comment]
@garygong It hasn't passed yet! 😉

**Comment by garygong** [comment]
Such a simple change...what could go wrong ;)

**Comment by interactivellama** [comment]
giphy

**Comment by interactivellama** [comment]
Image Snapshot testing with the following config

`customDiffConfig.threshold: 0.0`

```
const getMatchOptions = () => ({
	failureThreshold: 0.2,
	failureThresholdType: 'percent',
	// 0.02 appears to ignore slight gray changes in SLDS
	customDiffConfig: { threshold: 0.0 },
});
```

```
 Image Snapshots
    Image storyshots
      Inital Blank Story
        ✓ Placeholder (1024ms)
      SLDSAccordion
        ✓ Base (730ms)
        ✓ Base Open (579ms)
      SLDSAlert
        ✓ Info (511ms)
        ✓ Warning (527ms)
        ✓ Error (485ms)
        ✓ Offline (498ms)
        ✓ Dismissable (513ms)
        ✓ Close alert (477ms)
        ✓ Custom Class Names (516ms)
        ✓ Custom Styles (466ms)
      SLDSAvatar
        ✓ Base (696ms)
        ✓ Entity Icon (525ms)
        ✓ Entity Initials (518ms)
        ✓ User Icon (477ms)
        ✓ User Initials (456ms)
        ✓ Inverse User Initials (476ms)
      SLDSBrandBand
        ✕ Default (medium) (3438ms)
        ✓ Small (1130ms)
        ✕ Large (4121ms)
        ✓ No Image (580ms)
        ✓ Lightning Blue Theme (1112ms)
        ✕ Image with background size cover (4880ms)
      SLDSBreadcrumb
        ✓ 2 Items (493ms)
        ✓ 1 Item (462ms)
      SLDSBuilderHeader
        ✓ Base (560ms)
        ✓ Base with Toolbar (743ms)
        ✓ Successful Save (599ms)
        ✓ After Successful Save (632ms)
        ✓ Failed Save (644ms)
      SLDSButton
        ✓ Base (456ms)
        ✓ Neutral (437ms)
        ✓ Neutral with id (474ms)
        ✓ Neutral Icon (465ms)
        ✓ Disabled (509ms)
        ✓ Icon large (497ms)
        ✓ Icon with external path (493ms)
        ✓ Small Icon Hint inverse (490ms)
        ✓ Icon Container Small (467ms)
        ✓ Dropdown Icon inverse (509ms)
        ✓ Outline brand button (465ms)
        ✓ Doc site Base Neutral (500ms)
        ✓ Doc site Brand Disabled (471ms)
        ✓ Doc site Button Icons (561ms)
      SLDSButtonGroup
        ✓ More Icon (482ms)
        ✓ Icon Group (525ms)
        ✓ Checkbox (531ms)
        ✓ Checkbox Error (575ms)
        ✓ List Variant (483ms)
      SLDSButtonStateful
        ✓ Base (506ms)
        ✓ Disabled (479ms)
        ✓ Icon (502ms)
        ✓ Doc site Icon Text Button (486ms)
        ✓ Doc site Icon Button (461ms)
      SLDSCard
        ✓ w/ Items (822ms)
        ✓ Empty (635ms)
        ✓ Custom Header (833ms)
        ✓ Custom Heading (791ms)
        ✓ Set height card (799ms)
        ✓ w/o Header (729ms)
        ✓ Doc site Related List With Table (792ms)
      SLDSCheckbox
        ✓ Checkbox (default, indeterminate, required, disabled (474ms)
        ✓ Checkbox (assistive text) (611ms)
        ✓ Checkbox (checked) (459ms)
        ✓ Checkbox (indeterminate) (656ms)
        ✓ Checkbox Toggle (503ms)
        ✓ Checkbox Toggle (with error) (513ms)
        ✓ Checkbox Toggle (required) (528ms)
        ✓ Checkbox Toggle (disabled) (504ms)
        ✓ Checkbox Toggle (assistive text) (606ms)
        ✓ Checkbox Toggle (checked) (490ms)
        ✓ Doc site Error (536ms)
        ✓ Doc site Snapshot Base (611ms)
        ✓ Doc site Snapshot Toggle (650ms)
        ✓ Doc site Toggle (671ms)
      SLDSColorPicker
        ✓ Default (496ms)
        ✓ Custom Only (506ms)
        ✓ Swatch Only (487ms)
        ✓ Predefined Colors (538ms)
        ✓ Predefined Colors Only (494ms)
        ✓ Hidden Input (514ms)
        ✓ Custom Tab Selected (495ms)
        ✓ Outer Input in Error State (562ms)
        ✓ Working Color Input in Error State (502ms)
        ✓ Custom Validator (545ms)
        ✓ Color Picker Disabled (501ms)
        ✓ ColorPicker Menu Open (839ms)
        ✓ Doc site Default (495ms)
      SLDSCombobox
        ✓ Base (573ms)
        ✓ Base Pre-defined Options Only (565ms)
        ✓ Base Inline Help (618ms)
        ✓ Base Menu Item Disabled (586ms)
        ✓ Base Menu Item Disabled With Tooltip (552ms)
        ✓ Base Menu Item Disabled With Tooltip Open (1201ms)
        ✓ Inline Single Selection (510ms)
        ✓ Inline Multiple Selection (561ms)
        ✓ Base Custom Menu Item (533ms)
        ✓ Base Custom Menu Item Disabled (534ms)
        ✓ Base Menu Sub Headers (536ms)
        ✓ Base Menu Separator (547ms)
        ✓ Base Inherit Menu Width (518ms)
        ✓ Base Inherit Menu Width - Right to Left (RTL) (1291ms)
        ✓ Dialog (508ms)
        ✓ Readonly Single Selection (519ms)
        ✓ Readonly Single Selection - Right to Left (RTL) (570ms)
        ✓ Readonly Single Selection Disabled (514ms)
        ✓ Readonly Single Menu Item Disabled (521ms)
        ✓ Readonly Multiple Selection (514ms)
        ✓ Readonly Single Selection Custom Menu Item (558ms)
        ✓ Required Input in Error State (540ms)
        ✓ Input Component as a Prop (563ms)
        ✓ Snapshot Base Open (727ms)
        ✓ Snapshot Base Custom Menu Item Open (883ms)
        ✓ Snapshot Base Selected (572ms)
        ✓ Snapshot Base Label Required (577ms)
        ✓ Snapshot Base Open Menu Sub Header Separator (614ms)
        ✓ Snapshot Base Open Menu inheritWidthOf prop (624ms)
        ✓ Snapshot Dialog Open (640ms)
        ✓ Snapshot Inline Single Selection (508ms)
        ✓ Snapshot Inline Single Selection Selected (565ms)
        ✓ Snapshot Inline Multiple Selection (507ms)
        ✓ Snapshot Inline Multiple Selection Selected (540ms)
        ✓ Snapshot Readonly Single Selection (530ms)
        ✓ Snapshot Readonly Single Selection Disabled (516ms)
        ✓ Snapshot Readonly Single Selection Selected (497ms)
        ✓ Snapshot Readonly Single Selection Selected Open (680ms)
        ✓ Snapshot Readonly Multiple Selection (524ms)
        ✓ Snapshot Readonly Multiple Selection Single Item Selected (512ms)
        ✓ Snapshot Readonly Multiple Selection Multiple Items Selected (511ms)
        ✓ Snapshot Readonly Single Selection Custom Menu Item (760ms)
      SLDSExpandableSection
        ✓ Default (542ms)
        ✓ Controlled (585ms)
        ✓ Non-collapsible (556ms)
      SLDSFilter
        ✓ Filter (493ms)
        ✓ New Filter (517ms)
        ✓ Locked Filter (477ms)
        ✓ Permanant Filter (476ms)
        ✓ Filter Align Right (519ms)
        ✓ AssistiveTextFilter (504ms)
        ✓ ErrorFilter (522ms)
      SLDSDataTable
        ✓ Basic Fluid Layout (Default) (721ms)
        ✓ Basic Fluid Layout - Striped (727ms)
        ✓ Basic Fluid Layout - No Row Hover (722ms)
        ✓ Basic Fluid Layout - Column Bordered (738ms)
        ✓ Basic Fixed Layout (697ms)
        ✓ Advanced (Fixed Layout) (809ms)
        ✓ Advanced Single Select (Fixed Layout) (693ms)
        ✓ Advanced Single Select (Fixed Header) (707ms)
        ✕ Fixed Header (3253ms)
        ✓ Fixed Header Horizontal Scrolling (936ms)
      SLDSDynamicIcon
        ✓ Ellie (493ms)
        ✓ Eq (508ms)
        ✓ Score (472ms)
        ✓ Strength (460ms)
        ✓ Trend (466ms)
        ✓ Typing (473ms)
        ✓ Waffle (467ms)
      SLDSMenuDropdown
        ✓ Base (459ms)
        ✓ Base with icon (476ms)
        ✓ Render inline (471ms)
        ✓ Render inline w/ Nubbins (1246ms)
        ✓ Custom Trigger (465ms)
        ✓ Custom Content (476ms)
        ✓ Hover (510ms)
        ✓ Two Hovers (470ms)
        ✓ Checkmark (467ms)
        ✓ Hover with Checkmark (497ms)
        ✓ Controled w/ isOpen (546ms)
      SLDSGlobalHeader
        ✓ Search + Navigation (587ms)
        ✓ Fewer Elements (529ms)
        ✓ With custom <Avatar/> (582ms)
        ✓ Doc site Default (606ms)
      SLDSInput
        ✓ Base (634ms)
        ✓ Custom style and autocomplete (529ms)
        ✓ Base with Icons (1353ms)
        ✓ Fixed Text (540ms)
        ✓ Read Only (534ms)
        ✓ Static Input (539ms)
        ✓ Disabled Input (520ms)
        ✓ Required Input in Error State (656ms)
        ✓ Inline Help (548ms)
        ✓ Field Level Help (510ms)
        ✓ Field Level Help, Tooltip Open (579ms)
        ✓ Counter Input (962ms)
        ✓ Counter Static Input (505ms)
        ✓ Docs site Default (678ms)
        ✓ Docs site Error (594ms)
        ✓ Docs site Icons (582ms)
        ✓ Docs site InactiveInputs (569ms)
      SLDSIcon
        ✓ Category: Standard (523ms)
        ✓ Category: Utility (699ms)
        ✓ Category: Action (527ms)
        ✓ Category: Doctype (440ms)
        ✓ Category: Custom (477ms)
        ✓ Category: External Path (516ms)
        ✓ Size: X-Small (446ms)
        ✓ Size: Small (476ms)
        ✓ Size: Medium (default) (478ms)
        ✓ Size: Large (484ms)
        ✓ Color: Base (656ms)
        ✓ Color: Default (641ms)
        ✓ Color: Error (632ms)
        ✓ Color: Warning (653ms)
        ✓ Color: Light (654ms)
        ✓ Base: Standard (custom styles) (643ms)
        ✓ Base: Imported (589ms)
        ✓ Docs site Categories (704ms)
        ✓ Docs site Colors (511ms)
        ✓ Docs site Sizes (583ms)
      SLDSIllustration
        ✓ Small Image and Text (478ms)
        ✓ Large Image and Text (642ms)
        ✓ Heading Only (470ms)
        ✓ Message Only (463ms)
        ✓ Heading and Message (477ms)
      SLDSMediaObject
        ✓ Base (579ms)
        ✓ Figure Vertical Center (584ms)
        ✓ Docs site Default (535ms)
        ✓ Docs site VerticallyCentered (578ms)
      SLDSPageHeader
        ✓ Base (590ms)
        ✓ Base with actions (595ms)
        ✓ Record Home (truncates) (757ms)
        ✓ Object Home (694ms)
        ✓ Related List (663ms)
        ✓ Record Home (field updates) (764ms)
        ✓ Docs site RecordHome (708ms)
        ✓ Docs site RelatedList (677ms)
      SLDSPill
        ✓ Linked, Unlinked, Truncated (517ms)
        ✓ Icon, Avatar, Error (672ms)
        ✓ Docs site Snapshot (538ms)
      SLDSPillContainer
        ✓ Base Pill Container (502ms)
        ✓ Pill Container With Icons (614ms)
        ✓ Pill Container With Avatars (671ms)
        ✓ Bare Pill Container (510ms)
      SLDSPopover
        ✓ Header (509ms)
        ✓ Controlled w/ Footer (509ms)
        ✓ AlternativeHeader (524ms)
        ✓ Alignment (Button) (3528ms)
        ✓ Alignment (ButtonIcon) (3252ms)
        ✓ Custom Target (514ms)
        ✓ Custom Target - Open (706ms)
        ✓ Styling (dev-only) (730ms)
        ✓ Error (503ms)
        ✓ Error - Open (834ms)
        ✓ Warning (494ms)
        ✓ Warning  - Open (865ms)
        ✓ Walkthrough (496ms)
        ✓ Walkthrough - Open (840ms)
        ✓ Walkthrough Action (508ms)
        ✓ Walkthrough Action - Open (795ms)
        ✓ Edit Dialog (486ms)
        ✓ Edit Dialog  - Open (830ms)
      SLDSProgressIndicator
        ✓ Base (498ms)
        ✓ Base With Many Steps (485ms)
        ✓ Base With Disabled Steps (470ms)
        ✓ Step Error (501ms)
        ✓ In A Modal (With Step Error) - Needs DOM (693ms)
        ✓ Completed Progress (478ms)
        ✓ Vertical (610ms)
        ✓ VerticalStepError (710ms)
        ✓ SetupAssistant (890ms)
      SLDSProgressBar
        ✓ Default (442ms)
        ✓ Descriptive (488ms)
        ✓ Color (443ms)
        ✓ Radius (466ms)
        ✓ Thickness (520ms)
        ✓ Vertical (600ms)
      SLDSSpinner
        ✓ Small (612ms)
        ✓ Medium (628ms)
        ✓ Large (652ms)
        ✓ Brand Small (627ms)
        ✓ Brand Medium (623ms)
        ✓ Brand Large (636ms)
        ✓ Large with 300ms delay (633ms)
        ✓ Inverse Small (615ms)
        ✓ Inverse Medium (655ms)
        ✓ Inverse Large (664ms)
        ✓ Docs site Default (664ms)
      SLDSProgressRing
        ✓ Base (596ms)
        ✓ Theme: Active (597ms)
        ✓ Theme: Complete (587ms)
        ✓ Theme: Warning (616ms)
        ✓ Theme: Expired (600ms)
        ✓ Custom Icon (638ms)
        ✓ Snapshot Test Examples (664ms)
      SLDSRadio
        ✓ Base (612ms)
        ✓ Docs site Disabled (612ms)
      SLDSRadioGroup
        ✓ Base (710ms)
        ✓ Disabled (711ms)
        ✓ Required (712ms)
        ✓ Error (698ms)
        ✓ Docs site Base (684ms)
      SLDSRadioButtonGroup
        ✓ Base (676ms)
        ✓ Disabled (678ms)
        ✓ Required (680ms)
        ✓ Error (739ms)
        ✓ Docs site Base (667ms)
      SLDSScopedNotification
        ✓ Base (604ms)
        ✓ Light (771ms)
        ✓ Dark (857ms)
      SLDSSearch
        ✓ Standard (622ms)
      SLDSSetupAssistant
        ✓ Base Variant (1282ms)
        ✓ With Step Progress (1347ms)
        ✓ Hub with Expandable Steps (1705ms)
        ✓ In a Card (1435ms)
      SLDSSlider
        ✓ Slider (922ms)
        ✓ Disabled (673ms)
        ✓ Error (696ms)
        ✓ Vertical (641ms)
        ✓ Size: X-Small (664ms)
        ✓ Size: Small (653ms)
        ✓ Size: Medium (673ms)
        ✓ Size: Large (651ms)
        ✓ Docs site Sizes (752ms)
      SLDSSplitView
        ✓ Base: Open (1359ms)
        ✓ Base: Closed (708ms)
        ✓ Base: Multiple (1325ms)
        ✓ External State (1381ms)
        ✓ Custom List (1274ms)
      SLDSTabs
        ✓ Base (811ms)
        ✓ With disabled tab (825ms)
        ✓ Nested (726ms)
        ✓ Outside Control (874ms)
        ✓ Conditional (842ms)
        ✓ Unique Generated IDs (788ms)
        ✓ Scoped (929ms)
        ✓ Custom Tab Contents (715ms)
        ✓ Tab Intercept Panel Select (729ms)
      SLDSTextarea
        ✓ Standard (627ms)
        ✓ Disabled (641ms)
        ✓ Required (639ms)
        ✓ Error (694ms)
        ✓ Docs site Default (616ms)
        ✓ Docs site Disabled (650ms)
        ✓ Docs site Error (685ms)
      SLDSToast
        ✓ Info (741ms)
        ✓ Success (690ms)
        ✓ Warning (690ms)
        ✓ Error (708ms)
        ✓ Error With Details (759ms)
        ✓ Close Toast (623ms)
        ✓ Duration Toast (736ms)
        ✓ Custom Class Names (716ms)
        ✓ Custom Style (708ms)
      SLDSPopoverTooltip
        ✓ Base (635ms)
        ✓ Learn More (633ms)
        ✓ Button Group (679ms)
        ✓ Button (611ms)
        ✓ Open (750ms)
        ✓ Alignment (Button) (2720ms)
        ✓ Alignment (span) (2154ms)
        ✓ Alignment (icon) (2199ms)
      SLDSTree
        ✓ Base (586ms)
        ✓ Base with stencil (587ms)
        ✓ Initial Expanded/Selected (734ms)
        ✓ No Branch Select (567ms)
        ✓ Multiple Selection (602ms)
        ✓ Assistive Heading (539ms)
        ✓ Overflow Hidden (1464ms)
        ✓ Highlighted Search (629ms)
      SLDSVerticalNavigation
        ✓ Default (657ms)
        ✓ DOM Snapshot (693ms)
      SLDSVisualPicker
        ✓ Coverable (969ms)
        ✓ Non-Coverable (1061ms)
        ✓ Links (649ms)
        ✓ Vertical (1306ms)
        ✓ Vertical Coverable (1181ms)
```

**Comment by interactivellama** [comment]
I manually looked at the following components that are commented out of `story-based-tests.js`

```
// export AppLauncher from '../components/app-launcher/__docs__/storybook-stories';
// export GlobalNavigationBar from '../components/global-navigation-bar/__docs__/storybook-stories';
// export DatePicker from '../components/date-picker/__docs__/storybook-stories';
// export IconSettings from '../components/icon-settings/__docs__/storybook-stories';
// export Modal from '../components/modal/__docs__/storybook-stories';
// export Panel from '../components/panel/__docs__/storybook-stories';
// export TimePicker from '../components/time-picker/__docs__/storybook-stories';
```

All other components should have an image snapshot and they did not fail except brand band and fixed header DataTable. I looked at DataTable and it was fine.

**Comment by interactivellama** [comment]
Used #2111 instead of this pull request. Updating SLDS exposed weaknesses in image snapshot testing. Image snapshot testing was removed as a result.

**Pull request closed without merging**
