### PR TITLE
Fix AccordionPanel: application crashes if refs is not provided

### PR DESCRIPTION
**Pull request by sumukhah**
refs is not a required prop for the AccordinPanel component, but if we have not provided refs, refs will be undefined,
refs.summaryButton will not exist. This makes the app crash. This error will occur only if we use AccordinPanel
individually(Not as a child of Accordin). That is because Accordin component will pass refs by default.

This issue has fixed using a ternary expression. If refs exist then buttonRef takes refs.summaryButton otherwise
it will have a null value. Along with this, I have removed onClickSummary prop. as it is unused, throughout the component

Fixes: #2450

### CODE REVIEW

**Comment by sumukhah** [comment]
Hello,
I need some help to figure out what went wrong in my code.
It would be really helpful if somebody points out what I made mistake..

**Comment by burtek** [comment]
@sumukhah doesn't look like your fault.

@interactivellama will this get merged or sth?

**Comment by rainerbruemmer** [comment]
@sumukhah How did you solve your problem (without a merged pull request)? I have the same problem.

**Comment by sumukhah** [comment]
@rainerbruemmer, Manually copy and paste my pull request code in your code in respective files.

**Comment by rainerbruemmer** [comment]
> @rainerbruemmer, Manually copy and paste my pull request code in your code in respective files.

Ok, thank you. But that is not satisfying.

@interactivellama @shleewhite Are there any plans to merge this PR?

**Comment by interactivellama** [comment]
I'm cool with testing refs and returning `null`. `currButtonIndex` is used many, many times. Non-SLDS patterns are not robustly supported. What is the use case for an `AccordionPanel` outside an `Accordion`? Is there a link on the SLDS site you could share? https://www.lightningdesignsystem.com/

**Comment by burtek** [comment]
@interactivellama in my case it was that `AccordionPanel`s were grouped in `React.Fragment` for some reason (can't remember why now and I don't work there any more). See https://github.com/salesforce/design-system-react/issues/2450#issuecomment-580265827

**Comment by rainerbruemmer** [comment]
> What is the use case for an `AccordionPanel` outside an `Accordion`?
I implemented a react component which renders an `AccordionPanel` and contains some logic and an own state. So my `AccordionPanel` is use inside a `Accordion`, but wrapped in another component.

Monday I will replace my specialised `AccordionPanel` with the plain `AccordionPanel` and do the special things in a component which is given as a child. This solution is more clean and reusable (and hopefully working)

**Comment by interactivellama** [comment]
That sounds like an HOC. Maybe there's a way to pass the instance up?

https://github.com/christianalfoni/formsy-react/issues/308

**Pull request closed without merging**
