### PR TITLE
Button Fix For Close Alert and Toogle Alert

### PR DESCRIPTION
**Pull request by efemazlumoglu**

### CODE REVIEW

**Comment by interactivellama** [comment]
It looks like snapshot tests are failing.

**Comment by efemazlumoglu** [comment]
> It looks like snapshot tests are failing.

how to fix this, because cla is missing is another error that i get even if i signed in

**Comment by interactivellama** [comment]
@efemazlumoglu I believe our bot/app is broken at this time. https://github.com/salesforce/dr-cla/issues/39

**Comment by interactivellama** [comment]
Please re-open if updated!

**Pull request closed without merging**
