### PR TITLE
BuilderHeader: Add miscellaneous section

### PR DESCRIPTION
**Pull request by arshana**
added BUILDER_HEADER_MISC
added associated example
small fix to component/popover/edit_dialog.jsx
Issue #2242

### CODE REVIEW

**Comment by arshana** [comment]
@interactivellama Can you please review this?

**Comment by interactivellama** [comment]
@garygong Some design comments:

Icon should be white
Screen Shot 2019-09-09 at 10 34 59 AM

I'm not sure what a tooltip on a Builder Header looks like, but blue on blue could be an issue.
Screen Shot 2019-09-09 at 10 34 52 AM

**Comment by interactivellama** [comment]
@arshana Thank you for the edit dialog fix.

**Comment by interactivellama** [comment]
Looks good! Thanks @arshana for the contribution.

**Comment by interactivellama** [comment]
Fixes #2242

**Pull request merged**
