### PR TITLE
Support React fragment syntax

### LINKED ISSUE #1769: Update libraries to support `<>...</>` fragment syntax
Update react version, react-docgen, and any babel dependencies so that `<>...</>` fragment syntax is fully supported.

Related link: https://github.com/reactjs/react-docgen/issues/298

### PR DESCRIPTION
**Pull request by kevinparkerson**
Fixes #1769

Took a little fiddling but got it to work.

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [x] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [x] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [x] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [x] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [x] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [x] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by interactivellama** [comment]
#1821 Needs to go in before this.

**Comment by interactivellama** [comment]
After this update, `npm run dist` is is failing with unexpected tokens and missing babel plugins.

It looks like the babel CLI in `dist.sh` is ignorinng `.babelrc` settings.

**Comment by kevinparkerson** [comment]
> After this update, `npm run dist` is is failing with unexpected tokens and missing babel plugins.
> 
> It looks like the babel CLI in `dist.sh` is ignorinng `.babelrc` settings.

@interactivellama  looks like they added a new way to configure via `babel.config.js` If I add that file `npm run dist` succeeds, but then webpack fails for running locally. We might want to consider switching to that configuration style later, but for now to keep configuration all in one location I was able to specify the .babelrc file in `dist.sh` and it succeeds

**Comment by interactivellama** [comment]
These examples are not working in the doc site, since it is still on React 15. I will try to scope a user story for the doc site if I can't upgrade it in an hour or two

**Comment by interactivellama** [comment]
I've updated the doc site to React 16 and this code is working on it.

**Pull request merged**
