### PR TITLE
Create local ESLint plugin and rule to disallow double-dash (`--`) modifier class names

### LINKED ISSUE #1493: Use single underscore for BEM modifier classes instead of double-hyphen
As of the 2.3.1 release of [@salesforce-ux/design-system](https://github.com/salesforce-ux/design-system), it seems that the double-hyphen `--` syntax for CSS modifier classes has been deprecated in favor of a single underscore `_`.

From https://www.lightningdesignsystem.com/release-notes/:
> ## Release 2.3.1 - May 25, 2017
> ### Big Impact
> **BEM Naming Change**
> Initially we used the double dash style for BEM notation (--). Due to the fact that double dashes are problematic in an XML environment (which doesn't allow double dashes within comments), we have upgraded our syntax to use the single underscore style (_). This change is backward compatible for 18 months. But all components going forward are built with the single underscore BEM style.

Ironically, the markup on that page seems to still use the double-hyphen syntax.

If the single underscore is the recommended syntax going forward (and if the double-hyphen syntax will be removed in a few months), it would be great to switch the @salesforce/design-system-react components and the examples in the documentation to use the new syntax.

In our codebase, it has caused a mixed use of both syntaxes. I ended up writing an ESLint rule with a fixer to resolve the issue for us (which I'm happy to provide here as well if you think it will be useful).

### PR DESCRIPTION
**Pull request by sudowork**
Fixes #1493 

### Additional description

Creates a new plugin under `./eslint-plugin` containing the rule `no-double-dash-modifier`. This PR also then runs `eslint --fix` across the codebase (as well as some find/replace for ignored ESLint files and comments).

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [x] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [x] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [x] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [x] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [x] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [x] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by sudowork** [comment]
A couple manual steps I took to verify were to:
- Manually tab through all the storybook stories.
- Skim through snapshot updates.

**Comment by sudowork** [comment]
Hmm, it's possible that Travis doesn't like the local dependency (but I see a bunch of other warnings, so I'm not sure if Travis is just having issues.

**Comment by sudowork** [comment]
Looks like the error may be due to https://npm.community/t/issue-npm-install-with-local-packages-and-symlinks-enoent/518/12, which is unfortunate.

**Comment by interactivellama** [comment]
@amyleesalesforce You might be interested in this. It's an Eslint plugin for SLDS BEM to disallow double-dash (`--`) modifier class names.

**Comment by interactivellama** [comment]
I'm good with the local rules folder for now. I think I'd prefer a published npm module though, so we don't have to deal with any of this.

**Pull request merged**
