### PR TITLE
Replace airbnb shape props with PropTypes.shape

### PR DESCRIPTION
**Pull request by kevinlambert**
Airbnb prop types is redundant with PropTypes.shape.

### Additional description

---

### Pull Request Review checklist (do not remove)

* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at snapshot strings.
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by interactivellama** [comment]
My understanding is that `PropTypes.shape` requires all keys to be present, while Airbnb's allows for a subset to be present and only check to see that the keys are limited to the names specified. Is this false?

**Comment by interactivellama** [comment]
I could be wrong but I think the React PropType one forces all the keys while AirBnB's only forces it on `non-null/undefined value`.

`shape: takes a shape, and allows it to be enforced on any non-null/undefined value.` 
See https://www.npmjs.com/package/airbnb-prop-types

**Comment by interactivellama** [comment]
If it is different, sounds like a comment is needed in the source code for clarity. I'm going to close this and add a comment about non-null/undefined values unless we can verify that it's the same.

**Comment by interactivellama** [comment]
@kevinlambert I looked into this a little further and it appears that the behavior of `PropType.shape` has changed to match the behavior of air-bnb's. I'm not the only one confused it looks like: https://github.com/facebook/react/issues/5916

Apologies for jumping the gun on this "not working" without actually running the code. I was having flashbacks to trying to get `shape` working for days back in 2016, I think.

I'll update the merge conflicts and get back to you. Thanks!

**Comment by interactivellama** [comment]
Fixes: #1281

**Comment by kevinlambert** [comment]
Cool. No problem. I was also a bit confused by the docs too. :)

**Pull request merged**
