### PR TITLE
Add `dialogPosition` prop to Lookup as required for Dialog

### PR DESCRIPTION
**Pull request by NuclleaR**
Fixes issue #1213

### CODE REVIEW

**Comment by interactivellama** [comment]
Please update to `menuPosition` to align with [other components](https://github.com/salesforce/design-system-react/search?utf8=%E2%9C%93&q=menuPosition&type=)

**Comment by NuclleaR** [comment]
@interactivellama Could you pls review again

**Comment by interactivellama** [comment]
One more thing, please add something like:

```
// FOR BACKWARDS COMPATIBILITY
const menuPosition = this.props.isInline ? 'relative' : this.props.menuPosition; // eslint-disable-line react/prop-types
```
right before `<Dialog/>` to make it backwards compatible for folks. Here's an example https://github.com/salesforce/design-system-react/blob/master/components/combobox/combobox.jsx#L380

**Comment by interactivellama** [comment]
@NuclleaR Thank you for the fix!

**Pull request merged**
