### PR TITLE
fix dialog popper position bug in combobox search scenario

### LINKED ISSUE #1519: combobox dialog popover not repositioned properly when narrowing search results
When the dialog popover overflows the bottom of the viewport and flipped up in vertical direction, as you type in the search input box, the dialog popover results set is narrowed, but its position is not updated accordingly.

See screenshot below

screen shot 2018-08-30 at 3 31 49 pm

screen shot 2018-08-30 at 3 55 35 pm

### PR DESCRIPTION
**Pull request by qyiming**
Fixes #1519 

### Additional description

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [ ] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [ ] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by qyiming** [comment]
@interactivellama please take a look, thanks.

**Comment by interactivellama** [comment]
I'm still able to see the bug with this branch

screen shot 2018-08-31 at 4 56 25 pm

My modified `base.jsx` file from Combobox examples:

```
			<IconSettings iconPath="/assets/icons">
				<div style={{ marginTop: '500px' }}>
					<Combobox
						isOpen
						id="combobox-unique-id"
						disabled={this.props.disabled}
						events={{
							onChange: (event, { value }) => {
								if (this.props.action) {
									this.props.action('onChange')(event, value);
								} else if (console) {
									console.log('onChange', event, value);
								}
								this.setState({ inputValue: value });
							},
							onRequestRemoveSelectedOption: (event, data) => {
								this.setState({
									inputValue: '',
									selection: data.selection,
								});
							},
							onSubmit: (event, { value }) => {
								if (this.props.action) {
									this.props.action('onChange')(event, value);
								} else if (console) {
									console.log('onChange', event, value);
								}
								this.setState({
									inputValue: '',
									selection: [
										...this.state.selection,
										{
											label: value,
											icon: (
												<Icon
													assistiveText="Account"
													category="standard"
													name="account"
												/>
											),
										},
									],
								});
							},
							onSelect: (event, data) => {
								if (this.props.action) {
									this.props.action('onSelect')(
										event,
										...Object.keys(data).map((key) => data[key])
									);
								} else if (console) {
									console.log('onSelect', event, data);
								}
								this.setState({
									inputValue: '',
									selection: data.selection,
								});
							},
						}}
						labels={{
							label: 'Search',
							placeholder: 'Search Salesforce',
						}}
						multiple
						options={comboboxFilterAndLimit({
							inputValue: this.state.inputValue,
							limit: 10,
							options: accountsWithIcon,
							selection: this.state.selection,
						})}
						menuPosition="overflowBoundaryElement"
						selection={this.state.selection}
						value={this.state.inputValue}
					/>
				</div>
			</IconSettings>
```

**Comment by interactivellama** [comment]
Follow up, it is re-adjusting when I press the second letter. The menu jumps down below the input.

**Comment by interactivellama** [comment]
Maybe we could manipulate `this.state.triggerPopperJS` to true or maybe we could rework the popper callback? I'm not sure.

https://github.com/salesforce/design-system-react/blob/master/components/utilities/dialog/index.jsx#L357

**Comment by qyiming** [comment]
thanks for reviewing @interactivellama. I will check again why you still see the gap in the first case when you type 'z', it shouldn't. For the second case as you type 'zh' I think it's fine for the menu to jump below since there is now enough space at the bottom, or is that rather something you would not want?

**Comment by interactivellama** [comment]
Jumping below is fine.

**Comment by qyiming** [comment]
@interactivellama  I don't see this problem #1 you saw if I put the <div style={{ marginTop: '500px' }}> as a parent div of <IconSettings iconPath="/assets/icons"> in the original base.jsx. Not sure why putting the div under <IconSettings> and adding the isOpen=true attribute is making a differnce, among other changes that might be there in your snippet.

I tested my fix earlier by just adding a margin-top to the div of the input, it works fine. I should also mention that I've tested in the report builder and this fix works as expected when typing a first character trigger no results and resizes the dialog content when the dialog is flipped upward.

**Comment by interactivellama** [comment]
What do you think of something like this?

```
	componentWillUpdate (newProps, newState) {
		console.log('componentWillUpdate');
		if (this.popper) {
			console.log('scheduleUpdate');
			this.popper.scheduleUpdate();
		}
	},
```
We probably want popper to update itself anytime a prop changes, right? I'll dig into it deeper, but it seems like any change in options should probably trigger a realignment?

I don't think we want to create a new Popper object with `createPopper` each time.

**Comment by qyiming** [comment]
It actually works pretty well if we do the scheduleUpdate in the componentWillUpdate phase, and it's better since we are not recreating a new popper. I will make this change.

**Pull request merged**
