### PR TITLE
Remove any use of `javascript:` URLs

### LINKED ISSUE #2384: Prevent javascript URLs warning in React 16.9
@salesforce/design-system-react@0.10.12

React 16.9 emits the following warning:
```
Warning: A future version of React will block javascript: URLs as a security precaution. Use event 
handlers instead if you can. If you need to generate unsafe HTML try using 
dangerouslySetInnerHTML instead. React was passed "javascript:void(0);".
```

See facebook/react#16592 for the feature issue
And some related discussions here: facebook/react#16382

### PR DESCRIPTION
**Pull request by xoob**
Fixes #2384 and #2493

### Additional description

This maintenance change provides compatibility with React DOM 16.9, which introduced a deprecation warning for `javascript:` URLs in facebook/react#15047:

    Warning: A future version of React will block javascript: URLs as
    a security precaution. Use event handlers instead if you can. If you need
    to generate unsafe HTML try using dangerouslySetInnerHTML instead.

 - Replaces `<a href="javascript:void(0)">` with `<a href="#" onClick={(event) => event.preventDefault()}>` as suggested in facebook/react/issues/16382
 - Adds `EventUtil.trappedHandler()` utility to simplify the process of cancelling the event for an optional handler.
 - Adds a `href === '#'` conditional cancellation to some components, so they conform with prior behavior.

Changes have been smoke tested but require more detailed testing before they can be merged.

### To-Do

 - [ ] Test that all changed components are working as expected. We need instructions from the maintainer where to start and what to look for.

 - [ ] Discuss a11y warnings with maintainer. `npm test` now throws these warnings:

```
[test:accessibility]   ● aXe storyshots › Storyshots › SLDSBreadcrumb › 2 Items
[test:accessibility]
[test:accessibility]     Error
[test:accessibility]
[test:accessibility]       Error: expect(received).toHaveNoViolations(expected)
[test:accessibility]       Expected story to pass aXe accessibility tests.
[test:accessibility]       The following violations were found:
[test:accessibility]       RULE: skip-link: The skip-link target should exist and be focusable
[test:accessibility]       EXPECTED no violations in the following DOM nodes:
[test:accessibility]         #parent-entity
[test:accessibility]           This is a list of checks that, if none pass, will generate a violation. Fix ANY of the following to pass:
[test:accessibility]           - No skip link target
[test:accessibility]         a[href$="\#record"]
[test:accessibility]           This is a list of checks that, if none pass, will generate a violation. Fix ANY of the following to pass:
[test:accessibility]           - No skip link target
[test:accessibility]       Need more help? Please visit: https://dequeuniversity.com/rules/axe/3.2/skip-link?application=axe-puppeteer
```

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [ ] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by xoob** [comment]
Snapshot tests are failing. Is it okay to just refresh the snapshots? Anything I should look out for?

**Comment by garygong** [comment]
Awesome, thanks for taking this up!  Sorry for the delay in reviewing.  I'll take a look within a next few days.

**Comment by xoob** [comment]
@garygong, any more feedback about these changes? I'd like to get them merged before continuing on TypeScript compatibility...

**Comment by garygong** [comment]
> @garygong, any more feedback about these changes? I'd like to get them merged before continuing on TypeScript compatibility...

Sorry, I lot track of this.  I'll look at this in the next day or so!

**Comment by garygong** [comment]
@xoob The changes look good to me!  Thanks for taking this on!

Testing:  Running `npm run test` is a good place to start to verify that components are working as expected.  Also, it's also good to do manual verification in Storybook for the changed components.  I did a few spot checks and they are working for me!

A11y `skip-link` warnings:  Is it possible to avoid using the skip-link altogether?

Instead of:

`<a href="#entity">`

Use:

`<a href="#" onClick={(event) => event.preventDefault()}>`

**Comment by garygong** [comment]
I'll continue to work on this here: https://github.com/salesforce/design-system-react/pull/2829

**Pull request closed without merging**
