### PR TITLE
[Fix] Combobox ID 

### LINKED ISSUE #1711: [Accessibility] Combobox examples need unique IDs
Each Combobox example needs a unique ID. 

Currently, they have the same ID, so screen readers associate all of the labels with the first example.

I will fix the issue.

### PR DESCRIPTION
**Pull request by shleewhite**
Fixes #1711 

### Additional description

* gives each example a unique id with a random number

@donnieberg @interactivellama 

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [ ] `npm run lint:fix` has been run and linting passes.
* [ ] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by amateurhuman** [comment]
@shleewhite you've been added to the org, after you've accepted the invite you can refresh this check on the PR by going to https://cla.salesforce.com/status/salesforce/design-system-react/pull/1713

**Comment by interactivellama** [comment]
@shleewhite We have DOM snapshot tests running in the CI, so the ids need to be the same each time or the tests fail. https://travis-ci.org/salesforce/design-system-react/builds/478079854#L9269

**Comment by shleewhite** [comment]
@interactivellama ah, so instead of using a random number, should I use something like `combobox-1-id` for the base and manually number them from there?

**Comment by interactivellama** [comment]
I'd recommend something like the name of the variant such as `combobox-base`. No number needed.

You will want to run `npm run test:snapshot -- -u` and commit `tests/story-based-tests.snapshot-test.js` so that the DOM strings update. You can ignore the VRT/PNGs.

**Comment by interactivellama** [comment]
I believe the linter is failing due to `'` vs `"` in the React props. I'll pull down and check.

**Comment by shleewhite** [comment]
Thank you for helping! I didn't realize that was something the linter was checking for.

**Comment by interactivellama** [comment]
No problem. I'd recommend running `npm test` before pushing and `npm run lint:fix` should fix any small format issue like this in the future.

**Comment by interactivellama** [comment]
I should have a release out for you today.

**Pull request merged**
