### PR TITLE
Fixes storybook on Windows 10

### LINKED ISSUE #1441: Please provide a neat, well illustrated and elaborated documentation to how to install and run the project locally.
Please provide a complete guide and step by step process, from cloning git repo to running the project, because running locally having lots of errors while following a cliche process of running a npm
Example:
ERROR in ./components/accordion/__examples__/base.jsx
Module not found: Error: Can't resolve './components/accordion' in 'C:\lightningReact\design-system-react-master\design-system-react-master\components\accordion\__examples__'
 @ ./components/accordion/__examples__/base.jsx 12:40-73
 @ ./components/accordion/__docs__/storybook-stories.jsx
 @ ./components/storybook-stories.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/@storybook/react/node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
ERROR in ./components/accordion/__examples__/base.jsx
Module not found: Error: Can't resolve './components/accordion/panel' in 'C:\lightningReact\design-system-react-master\design-system-react-master\components\accordion\__examples__'
 @ ./components/accordion/__examples__/base.jsx 14:36-75
 @ ./components/accordion/__docs__/storybook-stories.jsx
 @ ./components/storybook-stories.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/@storybook/react/node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
ERROR in ./components/alert/__examples__/info.jsx
Module not found: Error: Can't resolve './components/alert' in 'C:\lightningReact\design-system-react-master\design-system-react-master\components\alert\__examples__'
 @ ./components/alert/__examples__/info.jsx 12:36-65
 @ ./components/alert/__docs__/storybook-stories.jsx
 @ ./components/storybook-stories.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/@storybook/react/node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
ERROR in ./components/alert/__examples__/error.jsx
Module not found: Error: Can't resolve './components/alert' in 'C:\lightningReact\design-system-react-master\design-system-react-master\components\alert\__examples__'
 @ ./components/alert/__examples__/error.jsx 12:36-65
 @ ./components/alert/__docs__/storybook-stories.jsx
 @ ./components/storybook-stories.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/@storybook/react/node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
ERROR in ./components/alert/__examples__/close-alert.jsx
Module not found: Error: Can't resolve './components/alert' in 'C:\lightningReact\design-system-react-master\design-system-react-master\components\alert\__examples__'
 @ ./components/alert/__examples__/close-alert.jsx 12:36-65
 @ ./components/alert/__docs__/storybook-stories.jsx
 @ ./components/storybook-stories.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/@storybook/react/node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
ERROR in ./components/alert/__examples__/custom-class-name.jsx
Module not found: Error: Can't resolve './components/alert' in 'C:\lightningReact\design-system-react-master\design-system-react-master\components\alert\__examples__'
 @ ./components/alert/__examples__/custom-class-name.jsx 12:36-65
 @ ./components/alert/__docs__/storybook-stories.jsx
 @ ./components/storybook-stories.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/@storybook/react/node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
ERROR in ./components/alert/__examples__/warning.jsx
Module not found: Error: Can't resolve './components/alert' in 'C:\lightningReact\design-system-react-master\design-system-react-master\components\alert\__examples__'
 @ ./components/alert/__examples__/warning.jsx 12:36-65
 @ ./components/alert/__docs__/storybook-stories.jsx
 @ ./components/storybook-stories.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/@storybook/react/node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
ERROR in ./components/alert/__examples__/offline.jsx
Module not found: Error: Can't resolve './components/alert' in 'C:\lightningReact\design-system-react-master\design-system-react-master\components\alert\__examples__'
 @ ./components/alert/__examples__/offline.jsx 12:36-65
 @ ./components/alert/__docs__/storybook-stories.jsx
 @ ./components/storybook-stories.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/@storybook/react/node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
ERROR in ./components/alert/__examples__/dismissable.jsx
Module not found: Error: Can't resolve './components/alert' in 'C:\lightningReact\design-system-react-master\design-system-react-master\components\alert\__examples__'
 @ ./components/alert/__examples__/dismissable.jsx 12:36-65
 @ ./components/alert/__docs__/storybook-stories.jsx
 @ ./components/storybook-stories.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/@storybook/react/node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
ERROR in ./components/alert/__examples__/error.jsx
Module not found: Error: Can't resolve './components/alert/container' in 'C:\lightningReact\design-system-react-master\design-system-react-master\components\alert\__examples__'
 @ ./components/alert/__examples__/error.jsx 14:40-79
 @ ./components/alert/__docs__/storybook-stories.jsx
 @ ./components/storybook-stories.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/@storybook/react/node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
ERROR in ./components/alert/__examples__/info.jsx
Module not found: Error: Can't resolve './components/alert/container' in 'C:\lightningReact\design-system-react-master\design-system-react-master\components\alert\__examples__'
 @ ./components/alert/__examples__/info.jsx 14:40-79
 @ ./components/alert/__docs__/storybook-stories.jsx
 @ ./components/storybook-stories.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/@storybook/react/node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
ERROR in ./components/alert/__examples__/warning.jsx
Module not found: Error: Can't resolve './components/alert/container' in 'C:\lightningReact\design-system-react-master\design-system-react-master\components\alert\__examples__'
 @ ./components/alert/__examples__/warning.jsx 14:40-79
 @ ./components/alert/__docs__/storybook-stories.jsx
 @ ./components/storybook-stories.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/@storybook/react/node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
ERROR in ./components/alert/__examples__/offline.jsx
Module not found: Error: Can't resolve './components/alert/container' in 'C:\lightningReact\design-system-react-master\design-system-react-master\components\alert\__examples__'
 @ ./components/alert/__examples__/offline.jsx 14:40-79
 @ ./components/alert/__docs__/storybook-stories.jsx
 @ ./components/storybook-stories.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/@storybook/react/node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
ERROR in ./components/alert/__examples__/close-alert.jsx
Module not found: Error: Can't resolve './components/alert/container' in 'C:\lightningReact\design-system-react-master\design-system-react-master\components\alert\__examples__'
 @ ./components/alert/__examples__/close-alert.jsx 14:40-79
 @ ./components/alert/__docs__/storybook-stories.jsx
 @ ./components/storybook-stories.js
 @ ./.storybook/config.js

and many more, let me know if i could resolve this issue....

### PR DESCRIPTION
**Pull request by futuremint**
Bumps version of bable-plugin-root-import and checks in a new package-lock file too.

Fixes #1441 

### Additional description

This was testing in VSCode on Windows 10 using [Git for Windows](https://gitforwindows.org/).

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [ ] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [ ] `npm run lint:fix` has been run and linting passes.
* [ ] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by interactivellama** [comment]
Please try now @AnutaK. I can't promise all the tests work, but `npm start`/Storybook should.

**Comment by interactivellama** [comment]
@AnutaK if you want to try `npm test` and file any issues with it, feel free to! There's nothing to hide here.

**Comment by futuremint** [comment]
The tests definitely *don't* work (due to the shell script we use to run them), but I'm also working on that issue this week as well.

**Comment by interactivellama** [comment]
@futuremint Thank you for picking up this task on such quick notice!

**Pull request merged**
