### PR TITLE
Datepicker maintain focus prop

### LINKED ISSUE #2285: Datepicker: Unable to enter date manually
When I click on Date input, I'm not able to enter date manually. Datepicker opens and forces me to select date. 

It reproduces on this example https://react.lightningdesignsystem.com/components/date-pickers/

### PR DESCRIPTION
**Pull request by BenjaminWFox**
Fixes #2285

### Additional description

Currently in the datepicker, interaction with the `Input` element moves focus to the `Calendar`. This PR adds an optional prop `canInputMaintainFocus` to the `Datepicker` which, when `true`, allows clicking & interacting with the input element without losing focus.

I'm unsure if solving this by adding an additional prop is acceptable, but there hadn't been any movement on this issue in the last month so I thought I would try. This could also be adapted into the new default behavior pretty easily.

I believe that with `canInputMaintainFocus` set to `true` all of the pattern bullet points are satisfied.

I added a story, but have not added a browser-test explicitly for this as I had trouble simulating the focus event. If that would be a requirement please let me know.

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [x] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [x] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [x] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [x] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by BenjaminWFox** [comment]
Sorry, this appears to have some commits from something I playing with some time ago. I will see if I can remove them from this PR, otherwise I will close this and submit a new PR.

**Comment by interactivellama** [comment]
Thank you so much for carrying this forward! @BenjaminWFox 

Apologies for the delay on the feedback. I think this is good pattern. It can be the default without the prop. You can remove the new prop.

The primary issue I see is that explicitly opening the menu with the right side icon should still focus on the menu day. It is currently not. The focus is staying on the icon

Something like a `menuOpenedByIcon` prop on `CalendarWrapper` would work and only be true when the icon is clicked, but not when the rest of the `input` is clicked into.

Here is a screenshot:
Screen Shot 2019-11-15 at 9 46 39 PM

**Comment by BenjaminWFox** [comment]
@interactivellama This is updated per your suggestions, let me know if any further edits are needed, thanks.

**Comment by interactivellama** [comment]
I pulled down and viewed in Storybook and the UX pattern is looking great! Give me a few days to look over the code and we should be good.

**Comment by interactivellama** [comment]
Thank you @BenjaminWFox for your work!

**Pull request merged**
