### PR TITLE
Group like files

### LINKED ISSUE #1157: Move tests and examples into source folder
I believe this will help with the contribution process.

 * Holistic component: Closer grouping of components, unit tests, and documentation. Unit tests and documentation (dev stories and doc site) are not afterthoughts or optional.
 * This is a monolith library, except that you can import a component individually.
 * Redefines Storybook stories as manual testing documentation
 * Increases discovery of "have to's" Not everyone reads the contributing/testing docs.
 * Reduces long relative import paths `../../../../`
 * Allows easier duplication of a component to start another one (you know you do this :-)
 * The React library itself _and_ the Jest library config groups unit tests with source by default. This is becoming a more common pattern.
 * Tighter file grouping equals less cognitive overhead when switching files.
 * Adds clarity to what files are compared to current file names.
 * Create __DUMMY__ folder that has a template for new components.
 
Tagging/npm scripts will need to be modified to clean more folders.

### New folder structure proposal
* components
    * \_\_shared__ (formerly utilities)
    * [COMPONENT NAME]
        * \_\_docs__
            * storybook-stories.jsx
            * site-stories.js
        * \_\_examples__
        * \_\_tests__
            * [COMPONENT].browser-test.js
            * [COMPONENT].snapshot-test.js
            * \_\_snapshots__
        * private
        * index.jsx [COMPONENT]

If we place examples that don't resolve properly out of the box (for instance the `~` root hack in our examples, then webpack may try to load them into context, even if they are not in use.

### PR DESCRIPTION
**Pull request by interactivellama**
Fixes #1157.   

@cormacmccarthy @chriscorwin Do you think this will be make it easier to know what to do to contribute a new component, even if you don't read the docs or anything?

This is built on top of #1150 

## Changes:
- moves all of the tests out of the `/tests/` directory and into the individual component's directory under the `/components/[component]/__tests__/` directory
- moves all of the examples out of the `/examples/` directory and into the individual component's directory under the `/components/[component]/__examples__/` directory

## Directory Tree Diffs:
Here you can more easily see where the files were move from/to
### /
root directory
### /components/
components
### /tests/
tests
### /components/accordian/
image

## Does it work? criteria:
* Tests work in browser on localhost:8001 and via CLI
* Storybook works on all pages
* `npm run dist` works and builds bundles in hidden folders
* can be imported and run by updated doc site branch: https://github.com/salesforce-ux/design-system-react-site/tree/new-dsr-file-structure (see `npm run local-update` in the site repo for local testing in sibling folders)

Then, any filename changes or opinions you have with enabling developers to contribute more easily or make the obvious way the correct way.

### CODE REVIEW

**Comment by interactivellama** [comment]
Updated with recent `IconSettings` PR.

**Comment by interactivellama** [comment]
Updated with recent `ProgressRing` PR.

**Comment by cormacmccarthy** [comment]
before:
image


after:
image

**Comment by interactivellama** [comment]
Eslint issues would make sense, we used to only test files under `components` folder. Now all the files are there. I'll update.

**Comment by interactivellama** [comment]
Updated. I'm guessing that since we don't have a package lock file (the debate is open for this feature in libraries) that you installed a new version of eslint settings.

**Comment by futuremint** [comment]
The fact that time passed, and running "npm install" broke things is a pretty good case for having a package lock file checked in.

**Comment by cormacmccarthy** [comment]
Old:
image


New:
image

Still don't quite have parity here. Not sure if this "matters" or not, but it definitely gives me pause.

**Comment by interactivellama** [comment]
Yeah, more of the tests and example files are being tested now that we are not just checking production files.

**Comment by interactivellama** [comment]
As to `package-lock.json`, I kinda like that this was found as opposed to manually updating the version and then finding it. Totally, could be an issue though for a new contributor though, so `package-lock.json` is they way to go and we will need a maintainer to try to break things--er...upgrade things every few months.

**Comment by cormacmccarthy** [comment]
- [X] Tests work in browser on localhost:8001 
image
- [X] Tests work by running `npm test`
image
- [X] Storybook works on all pages
image
- [ ] `npm run dist` works and builds bundles in hidden folders
image

Is this error a problem?
image
- [ ] can be imported and run by updated doc site branch: https://github.com/salesforce-ux/design-system-react-site/tree/new-dsr-file-structure (see `npm run local-update` in the site repo for local testing in sibling folders)
image

**Comment by cormacmccarthy** [comment]
@interactivellama there's just one open issue with this PR (see the doc site error above) before I can confirm it "works". At which point I'll go through and evaluate the actual changes themselves.

**Comment by interactivellama** [comment]
I'm not getting that build error:
screen shot 2017-11-30 at 9 46 59 pm

**Comment by cormacmccarthy** [comment]
@interactivellama That build error was a result of running `npm run local-update` from the site repo. It doesn't look like that's where you are based on your screenshot.

**Comment by cormacmccarthy** [comment]
Everything appears to be working locally. Llama pointed out that I was in master branch in the site repo and that that was what was causing the problem. In my own weak defense, I was pretty sick and probably shouldn't have been working 😖

Reviewing the actual content of the changes now.

**Comment by interactivellama** [comment]
Kevin Lambert contributed progress ring while this PR was open and it was merged into master. I didn't want to ask him to rewrite everything to this PR that wasn't in master.

the `__` comes from `__TESTS__` default/convention common in Jest framework. It's similar to the `_variable` is private thing. https://github.com/facebook/jest/issues/637

**Comment by interactivellama** [comment]
These should work now with latest push.

screen shot 2017-12-04 at 11 59 59 am

**Pull request merged**
