### PR TITLE
SLDSAccordian has 3 dropdowns in base whereas only 2 in base-open

### LINKED ISSUE #1830: SLDSAccordian has 3 dropdowns in base whereas only 2 in base-open
Thank you for filing an issue!

Please review the [frequently asked questions](faq.md) such as:

* [Why do my icons not show up in IE11?](browser-compatibility.md#internet-explorer-11-support)
* [Why aren't my ES6 imports, icons, styles, or fonts working in Create React App?](create-react-app.md)

Please include in your issue: SLDSAccordian has 3 dropdowns in base whereas only 2 in base-open. It should have 3 base-open dropdowns.

SLDSAccordian base
Annotation 2019-03-10 132552

SLDSAccordian base open
Annotation 2019-03-10 132649

* If you are working on the problem. Issues may be closed within 30 days if no one is assigned. Maintainers work on this project 20-30 hours per week and have their own prioritized backlog.
* How to duplicate a bug. Line numbers or code to paste into the documentation site examples is helpful.
* If you are a Salesforce employee. You should also create a duplicate work item in your internal ticket system and link to this issue.
* If you plan to work on a new component. Please propose props after reviewing at newly written components and `docs/codebase-overview.md`.

For Salesforce platform questions, please visit https://success.salesforce.com, https://partners.salesforce.com, or https://salesforce.stackexchange.com

This project uses SLDS markup, but you should submit HTML/CSS issues to https://github.com/salesforce-ux/design-system.

### PR DESCRIPTION
**Pull request by ashwaniYDV**
Fixes #1830 

### Additional description
SLDSAccordian has 3 dropdowns in base whereas only 2 in base-open. It should have 3 base-open dropdowns.
---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [ ] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [ ] `npm run lint:fix` has been run and linting passes.
* [ ] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by ashwaniYDV** [comment]
@interactivellama Please review these changes.

**Comment by pulkonet** [comment]
Hi, why do you think we need to have the same number of Accordians in both examples? Since they are just a showcase of closed and open accordians that we have to offer, I don't feel it is really necessary.

**Comment by ashwaniYDV** [comment]
Hi @pulkonet.
I thought that it would be more appropriate if both the cases are similar and everyone loves symmetry.

**Comment by interactivellama** [comment]
Yeah, not really a bug, but I'm willing to accept this change. Please review your tests.

**Comment by interactivellama** [comment]
@ashwaniYDV Please remove non-accordion PNG files. I apologize that they always get generated at this time.

**Comment by pulkonet** [comment]
@ashwaniYDV do you need help with this?

**Comment by interactivellama** [comment]
Thanks @ashwaniYDV ! I went ahead and updated the snapshots tests.

**Pull request merged**
