### PR TITLE
Allow nubbin to change position when popover flips

### LINKED ISSUE #1211: Popover looks wrong when changing position
[https://gyazo.com/0a3eee7bcdcedec09728142ca74c75ce](https://gyazo.com/0a3eee7bcdcedec09728142ca74c75ce)

• When there is room on screen, popover resizes and does not look good (the pointer is located at the top, and does not keep locked at the target button).

Would be nice to have an option to have pointer anchor to one position and not change position, or to have the popover alignment change (always keeping the pointer locked at the target) when there is limited room.

### PR DESCRIPTION
**Pull request by george-norris-salesforce**
Fixes #1211.

Allows the nubbin to change position when a popover flips

Before

[https://gyazo.com/d4a444546e61100ef2b532cd7e1eb255](https://gyazo.com/d4a444546e61100ef2b532cd7e1eb255)

After:

[https://gyazo.com/d419d7f31b8bb6c628722a326a233d75](https://gyazo.com/d419d7f31b8bb6c628722a326a233d75)
---

### Pull Request Review checklist (do not remove)

* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at snapshot strings.
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by interactivellama** [comment]
Ah sweet! Tell me when you want me to look at it. Looks like some lint issues are present.

**Comment by interactivellama** [comment]
@george-norris-salesforce I've added you as a collaborator. Please see email invite. That should give you rights to assign pull requests to me when you want to.

**Comment by interactivellama** [comment]
I went ahead and took a peak, cause I'm so excited. The non-orthogonal directions aren't showing arrows.

screen shot 2018-03-09 at 3 51 45 pm

Should look like:

screen shot 2018-03-09 at 3 52 18 pm

**Comment by george-norris-salesforce** [comment]
@interactivellama Just got back from PTO, taking a look now..

**Comment by interactivellama** [comment]
Closing @Vintik has worked this into #1404.

**Pull request closed without merging**
