### PR TITLE
Limit menu dropdown opening trigger keys

### LINKED ISSUE #2974: Dropdown: Limit menu opening trigger keys
The only keys that should open a MenuDropdown are: Spacebar, Enter, down arrow, and up arrow. Currently all non-modifier keys open a dropdown menu

### PR DESCRIPTION
**Pull request by Azmarie**
Fixes #2974

### Additional description

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [x] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [x] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [x] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [x] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [x] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] CircleCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by Azmarie** [comment]
Could you take a look? @interactivellama @alexxpan @gfyhui @alexzherdev, thank you.

**Review by alexzherdev — APPROVED** [review]
LGTM

**Comment by interactivellama** [comment]
Logic looks good to me.

**Comment by interactivellama** [comment]
@Azmarie  A unit test around the esc key being pressed is failing: https://app.circleci.com/pipelines/github/salesforce/design-system-react/122/workflows/bf7b05e8-dfc5-483b-8156-ad87e9f3387d/jobs/495

I'm guessing this is do to the logic change.

**Comment by interactivellama** [comment]
@Azmarie here's the Keyboard Support support spec we need to meet. https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html

**Comment by Azmarie** [comment]
Thank you for taking a look @interactivellama, I will fix the close Menu on `esc` case now.

**Review by alexzherdev — APPROVED** [review]

**Comment by interactivellama** [comment]
@alexzherdev @Azmarie Would either of you like to release? 
Here is how to do it. A `patch.md` file will trigger the build server to create a release build.
https://github.com/salesforce/design-system-react/pull/2973

**Pull request merged**
