### PR TITLE
Fix auto-align of selected item when combo-box is opened

### LINKED ISSUE #2745: Auto-align the selected item on the view when the combo-box is opened
When the combo-box is opened the item that's already selected doesn't get scrolled into view which means the user has to scroll down to get to the selected item. 
This is especially a problem for components like [year-picker](https://react.lightningdesignsystem.com/components/date-pickers/)(which uses the Read-only Combobox) in which the year range might start from 1900 making the user scroll a lot to get to the required selection.

Ideal behavior->

image

Ideally, item that's already selected should be on the bottom of the list when the box is opened.

### PR DESCRIPTION
**Pull request by chaitanyakaul**
Fixes #2745

### Additional description

This PR should fix the auto-align issue which affects sub-components like the `date-picker`. The item which is already selected should appear on the bottom of the combo-box view when it's opened.

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [ ] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [x] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [x] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [x] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by interactivellama** [comment]
The focus part is looking good. Please update the activeIndex to the selection, so that the keyboard navigation works. Pressing down should start at the selected item and move the gray from there. Currently it starts at item 0 (at the top).

**Comment by chaitanyakaul** [comment]
@interactivellama, Updated the code. Although it fixes the keyboard navigation, it causes two test-cases failures in the file `components/expression/__tests__/expression.browser-test.jsx` on lines 114 and 127. On exploring the cases, it seems they both are related to keyboard focus and down events. I think the ideal values should be equal to `ResourceList[0]` because of the behavior. Please correct me if I'm wrong.

**Comment by chaitanyakaul** [comment]
bump

**Comment by garygong** [comment]
I'll take a look at this today.

**Comment by interactivellama** [comment]
Excellent find! @chaitanyakaul Yes, Expression's tests should be updated to conform to the new behavior.

**Pull request merged**
