### PR TITLE
Add `brand` option in iconVariant

### LINKED ISSUE #1737: [Button component] variant is ignored when iconVariant is present
In SLDS button component, 'variant' is not applied if 'iconVariant' is present.

https://react.lightningdesignsystem.com/components/buttons/

For example - 

when `variant` is 'brand' and `iconVariant` is 'border', the search button does not have the brand color, it is

screen shot 2019-02-06 at 5 43 19 pm

whereas I expect it to be have the blue brand, similar to the following

screen shot 2019-02-06 at 5 47 29 pm

### PR DESCRIPTION
**Pull request by pradumangoyal**
Fixes #1737 

### Additional description

Actually, `iconVariant` is not ignored. The `brand` option was not present for `iconVariant`. The desired output(Icon button with brand color at background) can be obtained by setting `iconVariant` to `brand`.

image

The SLDS also have `brand` in the icon type as shown in the screenshot.

image

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [x] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [x] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [x] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
###### Required only if there are markup / UX changes
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by interactivellama** [comment]
@pradumangoyal Great find. I will add this to my review backlog. Thanks!

**Comment by interactivellama** [comment]
This is working for me visually, but the markup does not match https://www.lightningdesignsystem.com/components/button-icons/

`slds-button_icon` isn't present for

```
					<Button
						assistiveText={{ icon: 'Icon Bare Small' }}
						iconCategory="utility"
						iconName="settings"
						iconVariant="brand"
						variant="icon"
					/>
```

**Comment by pradumangoyal** [comment]
@interactivellama, I have seen to it actually `slds-button_icon` className was not present in it for any type of button. I have added 'slds-button_icon': isIcon` to the `getClassName` function for the button component which provides required class whenever the variant of the button is passed as `icon` which produce the following markup.

image

**Comment by pradumangoyal** [comment]
@interactivellama, I have updated which change the markup to required but causing Travis to fail. Should I update and push the snapshots?

**Pull request closed without merging**
