### PR TITLE
Teach 'npm start' to start foreground processes

### LINKED ISSUE #2527: Crtl+C on 'npm start' does not stop browser-tests-app
This change tells 'npm start' to run the two servers with 'concurrently', to avoid the background process not exiting correctly. We noticed that node tests/browser-tests-app stays alive if npm start is killed with Ctrl-C.

### PR DESCRIPTION
**Pull request by xoob**
Fixes #2527

This change tells 'npm start' to run the two servers with 'concurrently', to avoid the background process not exiting correctly. We noticed that `node tests/browser-tests-app` stays alive if `npm start` is killed with Ctrl-C.

---

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [x] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [x] `npm run lint:fix` has been run and linting passes.
* [x] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [x] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [x] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [x] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [x] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### CODE REVIEW

**Comment by garygong** [comment]
@kmmkwong Could you take a quick look at this?  Thanks a lot!

**Comment by kmmkwong** [comment]
Related issue - 
https://github.com/salesforce/design-system-react/issues/2527

**Comment by xoob** [comment]
@kmmkwong How do we proceed from here, who needs to approve this change so it can get merged?

**Comment by kmmkwong** [comment]
@xoob My apologies for the delay! I didn't have access so I was waiting for that.  Also you would need an issue logged for this.  I actually logged one but I couldn't link them.  let me see if I can find it.
  
@garygong can you please provide the access that I need.

**Comment by xoob** [comment]
> Also you would need an issue logged for this. I actually logged one but I couldn't link them.

I've linked them and added #2527 to the description @kmmkwong

**Comment by garygong** [comment]
LGTM!  Thanks a lot!

**Pull request merged**
