### PR TITLE
Menu Dropdown Value Change

### LINKED ISSUE #1458: Menu Dropdown Value Change
Hi - I recently ran into an issue with the `MenuDropdown` component:

When calling `getIndexByValue()` when `props.value` changes, the index of the value should be looked for in `nextProps.options,` instead of `this.props.options`. It is possible that a new list of options is passed in, and the code should be looking for the index of the value in the new options (not the existing ones). 

In our case, we have an initial `props.value` with an empty `props.options` array. Then, after an async call, we populate `props.options` with a new list of options that includes `props.value`. This triggers `componentWillReceiveProps()` of `MenuDropdown`, which calls `this.setCurrentSelectedIndices(nextProps)`. The `getIndexByValue()` returns -1 because we are not looking for the value in the new options list.

I can look into this issue and create a PR to fix this. Thanks!

### PR DESCRIPTION
**Pull request by alexxpan**
Fixes #1458

### Additional description

When the dropdown value is being changed in `nextProps`, we are passing in `nextProps.options` along with `nextProps.value`, to handle the case where the options list changes and we are selecting a value within this new options list.

### CONTRIBUTOR checklist (do not remove)
Please complete for every pull request

* [ ] First-time contributors should sign the Contributor License Agreement. It's a fancy way of saying that you are giving away your contribution to this project. If you haven't before, wait a few minutes and a bot will comment on this pull request with instructions.
* [ ] `npm run lint:fix` has been run and linting passes.
* [ ] Mocha, Jest (Storyshots), and `components/component-docs.json` CI tests pass (`npm test`).
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

### REVIEWER checklist (do not remove)

* [ ] TravisCI tests pass. This includes linting, Mocha, Jest, Storyshots, and `components/component-docs.json` tests.
* [ ] Tests have been added for new props to prevent regressions in the future. See [readme](https://github.com/salesforce/design-system-react/blob/master/tests/README.md).
* [ ] Review the appropriate Storybook stories. Open [http://localhost:9001/](http://localhost:9001/).
* [ ] The Accessibility panel of each Storybook story has 0 violations (aXe). Open [http://localhost:9001/](http://localhost:9001/).
* [ ] Review tests are passing in the browser. Open [http://localhost:8001/](http://localhost:8001/).
* [ ] Review markup conforms to [SLDS](https://www.lightningdesignsystem.com/) by looking at [DOM snapshot strings](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
* [ ] Add year-first date and commit SHA to `last-slds-markup-review` in `package.json` and push.
* [ ] Request a review of the deployed Heroku app by the Salesforce UX Accessibility Team.
* [ ] Add year-first review date, and commit SHA, `last-accessibility-review`, to `package.json` and push.
* [ ] While the contributor's branch is checked out, run `npm run local-update` within locally cloned [site repo](https://github.com/salesforce-ux/design-system-react-site) to confirm the site will function correctly at the next release.

### CODE REVIEW

**Comment by alexxpan** [comment]
I looked at the component tests but didn't feel it was necessary to add one for this use case. Let me know otherwise.

**Comment by jamesward** [comment]
@alexxpan You have an invite to this org at: https://github.com/salesforce

Once accepted refresh the CLA bot: https://cla.salesforce.com/status/salesforce/design-system-react/pull/1459

**Comment by interactivellama** [comment]
@alexxpan Thanks for the pull request. We'll try to get it looked at in the next week.

@futuremint Could you review this? Seems like we may not be getting our internal state right (and updating when props change).

**Comment by davidlygagnon** [comment]
@interactivellama I worked on this PR with @alexxpan (he's on my team). Do you think we can get this in soon enough for feature freeze?

**Comment by futuremint** [comment]
@interactivellama I read through the code and it looks ok to me. The only internal state derived from props are for the selectedIndices, and those are updated from `componentWillRecieveProps`.  However we should probably add some unit tests around controlled components and making sure they keep their state synced after prop changes.

**Pull request merged**
